<a href="https://colab.research.google.com/github/Saloni1707/ImageCompression/blob/main/PCAfromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PCA -> This has really intrigued me how interesting is this that we can reduce the dimensionality of the data points.
This makes me think further about the atoms that are present inside the molecules the high dimensional space with so many features
Stuff only gets more & more interesting.Will dive deeper soon!

In [8]:
#1.Standardize dataset
import pandas as pd
import numpy as np
import seaborn as sns

In [15]:
iris =sns.load_dataset('iris')
X=iris.drop(columns=['species']).to_numpy()


In [16]:
def covariance_matrix(X, n_rows):
    covariance_matrix = sum([
        X[i].reshape(-1,1) @ X[i].reshape(1,-1)
        for i in range(n_rows)
    ]) / n_rows
    return covariance_matrix

cov_matrix = covariance_matrix(X, 150)
print(cov_matrix)

[[34.82566667 17.82286667 23.22506667  7.52093333]
 [17.82286667  9.536      11.162       3.54593333]
 [23.22506667 11.162      17.21806667  5.79406667]
 [ 7.52093333  3.54593333  5.79406667  2.01553333]]


In [ ]:
#figuring out the further math!